on:
  schedule:
    - cron: "0 8 * * 1"
  push:
  workflow_dispatch:

jobs:
  ingest:
    name: ETL
    runs-on: ubuntu-latest
    environment: OS
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install deps
      run: npm install

    - name: Run ETL
      env:
        OS_ENDPOINT: ${{ secrets.OS_ENDPOINT }}
        OS_USERNAME: ${{ secrets.OS_USERNAME }}
        OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        OS_BACKFILL: "false"
      run: npm run etl
